server:
  port: 9000
app:
  name: Invivoo Products Catalog
  description: ${app.name} is a spring boot app that demonstrates how to use use Spring Boot to create a simple web service

---
spring:
  profiles: log-debug

logging.level:
  root: INFO
  com.invivoo.catalog.domain: DEBUG
  com.invivoo.catalog.interfaces: DEBUG
  org.springframework.web: WARN
  org.hibernate.SQL: INFO

---
spring:
  profiles: development
spring.profiles.include: log-debug
server:
  port: 9001
